In [40]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

In [41]:
df = pd.read_csv("/Users/miaalfonso/Desktop/HW/Assignment2/Pyrolysis.csv")
#/Pyrolysis.csv

In [42]:
df.head(10)

,INDEX,11FI05101,11FC05031,11FC05032,11FC05033,11FC05034,11FC05035,11FC05036,11FC05041,11FC05042,...,11TI05005,11TI05006,11TI05011,11TI05012,11TI05013,11TI05014,11TI05015,11TI05016,11TI05044,11TC05000
0,11/6/2015 0:00,52221.63426,8326.643312,8514.593137,8772.479316,8702.662279,8725.061214,8925.859148,4231.776051,4235.679965,...,611.155410,617.949135,835.685702,832.775546,837.579875,835.185782,837.532533,840.083021,1014.203860,838.564984
1,11/6/2015 0:20,52265.90033,8365.639417,8556.450386,8785.182039,8691.885549,8703.588278,8947.979539,4234.084322,4235.981084,...,608.830187,615.503000,842.786275,857.657809,842.063391,831.472131,827.847198,829.859649,1003.212185,838.303879
2,11/6/2015 0:40,52175.42222,8399.151486,8958.929290,8866.258307,8568.940794,8487.709325,8657.917877,4219.596998,4227.073918,...,612.223661,619.237611,832.882359,829.082685,836.141160,835.556342,839.504382,844.880867,1012.859396,837.527600
3,11/6/2015 1:00,52301.05859,8371.304905,8755.843789,8816.456687,8648.966226,8614.722260,8805.725760,4235.860665,4242.020290,...,610.773671,617.620987,836.430164,833.785133,840.057993,838.177957,834.462237,833.534243,1011.943218,837.818136
4,11/6/2015 1:20,52294.35381,8395.126075,8939.937799,8868.780738,8602.885921,8493.646648,8679.958967,4240.078093,4221.425555,...,610.275413,617.500575,839.643744,851.533809,842.807576,835.302639,827.123134,825.370441,1005.692422,837.338927
5,11/6/2015 1:40,52265.03067,8365.504310,8780.852987,8841.769575,8656.124079,8539.637431,8758.329774,4241.184508,4236.680896,...,614.795906,621.519133,828.617602,822.644381,836.985703,842.641434,846.149610,848.040651,1011.333829,838.378828
6,11/6/2015 2:00,52200.32884,8273.890963,8515.235562,8786.784298,8692.363442,8774.243705,8967.026779,4227.987909,4236.520722,...,612.785978,619.107429,833.482935,828.335641,835.280010,834.854151,842.489960,846.319539,1011.952702,838.397351
7,11/6/2015 2:20,52269.12703,8314.212554,8517.783165,8764.371424,8669.526376,8749.136641,8969.312003,4243.729509,4239.212231,...,610.077595,616.231543,838.175630,836.514478,837.539181,835.482164,834.876669,834.787851,1011.934926,838.346716
8,11/6/2015 2:40,52240.59940,8315.588421,8502.105429,8762.184962,8694.639345,8768.796221,8997.852215,4226.130267,4222.527552,...,610.812614,617.410995,833.344771,834.037237,838.906332,835.595273,838.255026,839.087380,1013.971608,837.788338
9,11/6/2015 3:00,52225.27030,8341.256788,8598.113528,8773.121815,8710.417790,8684.650514,8837.625346,4230.446723,4228.662087,...,608.823574,615.968486,838.156932,844.650030,839.914932,835.636618,831.449296,829.857540,1011.881495,837.489552

In [43]:

df = df.drop(df.columns[0], axis=1)

df.head(15)

,11FI05101,11FC05031,11FC05032,11FC05033,11FC05034,11FC05035,11FC05036,11FC05041,11FC05042,11FC05043,...,11TI05005,11TI05006,11TI05011,11TI05012,11TI05013,11TI05014,11TI05015,11TI05016,11TI05044,11TC05000
0,52221.63426,8326.643312,8514.593137,8772.479316,8702.662279,8725.061214,8925.859148,4231.776051,4235.679965,4331.376363,...,611.155410,617.949135,835.685702,832.775546,837.579875,835.185782,837.532533,840.083021,1014.203860,838.564984
1,52265.90033,8365.639417,8556.450386,8785.182039,8691.885549,8703.588278,8947.979539,4234.084322,4235.981084,4331.812712,...,608.830187,615.503000,842.786275,857.657809,842.063391,831.472131,827.847198,829.859649,1003.212185,838.303879
2,52175.42222,8399.151486,8958.929290,8866.258307,8568.940794,8487.709325,8657.917877,4219.596998,4227.073918,4335.506624,...,612.223661,619.237611,832.882359,829.082685,836.141160,835.556342,839.504382,844.880867,1012.859396,837.527600
3,52301.05859,8371.304905,8755.843789,8816.456687,8648.966226,8614.722260,8805.725760,4235.860665,4242.020290,4330.784367,...,610.773671,617.620987,836.430164,833.785133,840.057993,838.177957,834.462237,833.534243,1011.943218,837.818136
4,52294.35381,8395.126075,8939.937799,8868.780738,8602.885921,8493.646648,8679.958967,4240.078093,4221.425555,4324.309267,...,610.275413,617.500575,839.643744,851.533809,842.807576,835.302639,827.123134,825.370441,1005.692422,837.338927
5,52265.03067,8365.504310,8780.852987,8841.769575,8656.124079,8539.637431,8758.329774,4241.184508,4236.680896,4330.445724,...,614.795906,621.519133,828.617602,822.644381,836.985703,842.641434,846.149610,848.040651,1011.333829,838.378828
6,52200.32884,8273.890963,8515.235562,8786.784298,8692.363442,8774.243705,8967.026779,4227.987909,4236.520722,4338.350699,...,612.785978,619.107429,833.482935,828.335641,835.280010,834.854151,842.489960,846.319539,1011.952702,838.397351
7,52269.12703,8314.212554,8517.783165,8764.371424,8669.526376,8749.136641,8969.312003,4243.729509,4239.212231,4333.444938,...,610.077595,616.231543,838.175630,836.514478,837.539181,835.482164,834.876669,834.787851,1011.934926,838.346716
8,52240.59940,8315.588421,8502.105429,8762.184962,8694.639345,8768.796221,8997.852215,4226.130267,4222.527552,4336.756831,...,610.812614,617.410995,833.344771,834.037237,838.906332,835.595273,838.255026,839.087380,1013.971608,837.788338
9,52225.27030,8341.256788,8598.113528,8773.121815,8710.417790,8684.650514,8837.625346,4230.446723,4228.662087,4332.970272,...,608.823574,615.968486,838.156932,844.650030,839.914932,835.636618,831.449296,829.857540,1011.881495,837.489552
10,52229.49497,8386.592114,8750.592034,8816.606556,8672.125499,8589.925667,8748.082220,4236.784196,4242.680809,4326.294172,...,610.057237,618.103742,835.838981,834.769025,836.772254,835.751235,836.973816,838.843942,1009.964531,838.058563
11,52247.57528,8362.145272,8678.276813,8791.176895,8690.078192,8661.420643,8818.135037,4232.385402,4231.488776,4330.087647,...,610.042510,617.618632,837.422456,834.070547,836.556291,834.038305,836.958407,839.519462,1011.980543,837.512957
12,52269.99396,8368.814208,8569.900133,8776.540036,8710.702315,8726.630985,8881.761873,4223.144938,4221.156850,4335.786775,...,611.139216,618.345079,832.061841,832.519818,839.394275,836.619037,840.211482,842.021191,1013.784021,838.153886
13,52203.59113,8347.281596,8578.319180,8797.154602,8713.803774,8690.696467,8852.315235,4241.262173,4229.139885,4332.471201,...,609.572760,617.275449,835.856257,848.609898,841.017550,837.047228,832.475615,834.148954,1004.749397,838.584999
14,52230.63117,8373.500347,8973.696556,8890.995487,8627.002391,8518.133575,8599.772701,4227.353581,4228.813101,4342.918460,...,609.971050,618.348757,834.295249,833.363953,836.804572,836.351529,835.637772,837.067249,1010.149329,837.406803

In [44]:
df.describe()

,11FI05101,11FC05031,11FC05032,11FC05033,11FC05034,11FC05035,11FC05036,11FC05041,11FC05042,11FC05043,...,11TI05005,11TI05006,11TI05011,11TI05012,11TI05013,11TI05014,11TI05015,11TI05016,11TI05044,11TC05000
count,6669.000000,6669.000000,6669.000000,6669.000000,6669.000000,6669.000000,6669.000000,6669.000000,6669.000000,6669.000000,...,6669.000000,6669.000000,6669.000000,6669.000000,6669.000000,6669.000000,6669.000000,6669.000000,6669.000000,6669.000000
mean,52086.607263,8712.582010,8287.932362,8842.522833,8603.680748,8444.248226,8865.866092,4297.905730,4452.905547,4365.018466,...,617.811929,622.511101,831.648208,836.780286,835.400132,836.319523,837.300782,837.903612,1027.474983,837.910011
std,464.738337,121.623591,120.638306,95.786130,107.469695,112.196548,106.172983,40.376338,42.363111,24.027639,...,3.940449,2.917192,1.910854,2.236806,1.922875,1.811575,2.094034,2.244648,10.038618,1.285605
min,45736.531250,7466.118164,7110.184570,7652.420410,7561.086914,7439.499512,7731.586426,4147.067871,4204.664050,4241.510682,...,603.491333,611.425110,804.398743,809.329590,810.840485,812.086029,811.762329,811.068131,980.803802,813.534363
25%,52080.425780,8674.464844,8250.759766,8816.666992,8557.800781,8409.102539,8819.564453,4277.095703,4445.440693,4351.510742,...,614.694580,620.329590,830.853425,836.122177,834.470825,835.493164,836.341479,836.836578,1019.737488,837.743379
50%,52136.097660,8731.911133,8286.455078,8849.289063,8605.119141,8459.644902,8884.833008,4288.175293,4462.412109,4363.266113,...,618.976257,622.934143,831.628509,836.826157,835.474991,836.345734,837.407837,838.015167,1029.567841,837.979076
75%,52197.140630,8777.038086,8320.266851,8883.692383,8672.966798,8504.736328,8927.785156,4300.790039,4474.368161,4376.137695,...,620.939880,624.776916,832.425751,837.532196,836.445328,837.252701,838.400406,839.075317,1035.154907,838.240967
max,53489.472660,9053.129883,9278.496829,9080.204688,8854.346362,8805.973330,9129.166016,4469.789063,4630.651488,4493.321627,...,625.199951,629.285584,846.023840,865.560687,845.728282,843.780106,846.446014,850.595634,1045.856140,841.106018

In [45]:
df.shape

(6669, 27)

In [46]:
df.columns = df.columns.str.upper()

In [47]:
df.isnull().sum().sum()

0

In [48]:
df_drop_dup = df.drop_duplicates()

In [49]:
x_train, x_test = train_test_split(df, test_size = 0.2, random_state=42)
x_train2, x_val = train_test_split(x_train, test_size=0.2, random_state=42)

In [50]:
print(len(x_train2))
print(len(x_test))
print(len(x_val))

4268
1334
1067

In [51]:
x_train2.head()

,11FI05101,11FC05031,11FC05032,11FC05033,11FC05034,11FC05035,11FC05036,11FC05041,11FC05042,11FC05043,...,11TI05005,11TI05006,11TI05011,11TI05012,11TI05013,11TI05014,11TI05015,11TI05016,11TI05044,11TC05000
1708,52207.94141,8798.546875,8305.599609,8823.268555,8549.691406,8445.952148,8908.294922,4273.287109,4450.273438,4346.487305,...,612.050415,617.140198,829.717285,835.615952,835.315430,837.302399,835.314667,835.647324,1016.192139,837.526184
4587,52374.97266,8817.423828,8329.680664,8934.520508,8531.824219,8333.949219,8905.106445,4323.045410,4463.359863,4336.493164,...,621.200073,622.230591,830.896362,837.106705,836.830063,840.468918,838.225723,835.692673,1035.713257,838.323975
1299,52011.66016,8658.908203,8315.505859,8852.797852,8696.616211,8521.251953,8794.561523,4269.605957,4452.178711,4340.981445,...,618.643250,624.181580,830.888840,834.692688,833.603500,835.662369,837.995087,840.396408,1019.881866,837.797424
5554,52178.44141,8663.466797,8234.442383,8848.677734,8642.875977,8523.445313,8953.424805,4277.571289,4460.390625,4376.137695,...,618.796570,623.717529,832.035965,837.286621,833.581222,835.270798,838.281891,838.850265,1036.590759,837.970154
6276,52236.12891,8721.544922,8302.000977,8860.457031,8695.295898,8413.992188,8811.828125,4392.283691,4407.360352,4402.760254,...,619.826904,625.432739,831.679153,836.998993,836.678360,835.223206,836.229553,837.833313,1037.438171,837.910950

In [52]:
x_val.head()

,11FI05101,11FC05031,11FC05032,11FC05033,11FC05034,11FC05035,11FC05036,11FC05041,11FC05042,11FC05043,...,11TI05005,11TI05006,11TI05011,11TI05012,11TI05013,11TI05014,11TI05015,11TI05016,11TI05044,11TC05000
312,52297.87530,8723.629027,8414.601351,8978.936127,8728.525156,8476.896585,8707.959916,4317.244260,4475.694715,4382.078569,...,613.053704,621.308939,829.077955,838.089229,837.974657,835.893193,834.454472,838.130248,1009.069481,838.386695
1150,52068.23438,8614.025391,8310.293945,8883.298828,8760.723633,8512.702148,8733.216797,4263.770020,4447.328125,4366.420898,...,619.319336,626.523315,832.059433,836.481949,837.019867,838.737030,835.544861,835.905594,1022.294434,838.197571
4954,52129.52344,8891.151367,8379.805664,8905.736328,8411.178711,8222.392578,8918.781250,4283.020996,4447.775879,4361.747070,...,621.176880,622.205505,831.023727,837.854263,834.359192,836.330673,837.347610,836.875900,1034.029480,838.143310
718,52062.74702,8661.287538,8328.836978,8800.907053,8701.650901,8559.519069,8763.804583,4305.843316,4449.094517,4350.431879,...,610.442873,618.239611,830.583530,835.679614,835.179054,836.674637,836.034004,837.126103,1012.932533,837.832185
2215,52119.84766,8765.071289,8304.974609,8879.394531,8599.152344,8358.967773,8918.940430,4294.308594,4455.752441,4342.018066,...,615.382202,619.053162,833.553818,838.574982,834.976791,838.035889,836.049484,835.334503,1021.097565,837.862183

In [53]:
scaler = StandardScaler().fit(x_train2)

In [55]:
x_train2

,11FI05101,11FC05031,11FC05032,11FC05033,11FC05034,11FC05035,11FC05036,11FC05041,11FC05042,11FC05043,...,11TI05005,11TI05006,11TI05011,11TI05012,11TI05013,11TI05014,11TI05015,11TI05016,11TI05044,11TC05000
1708,52207.94141,8798.546875,8305.599609,8823.268555,8549.691406,8445.952148,8908.294922,4273.287109,4450.273438,4346.487305,...,612.050415,617.140198,829.717285,835.615952,835.315430,837.302399,835.314667,835.647324,1016.192139,837.526184
4587,52374.97266,8817.423828,8329.680664,8934.520508,8531.824219,8333.949219,8905.106445,4323.045410,4463.359863,4336.493164,...,621.200073,622.230591,830.896362,837.106705,836.830063,840.468918,838.225723,835.692673,1035.713257,838.323975
1299,52011.66016,8658.908203,8315.505859,8852.797852,8696.616211,8521.251953,8794.561523,4269.605957,4452.178711,4340.981445,...,618.643250,624.181580,830.888840,834.692688,833.603500,835.662369,837.995087,840.396408,1019.881866,837.797424
5554,52178.44141,8663.466797,8234.442383,8848.677734,8642.875977,8523.445313,8953.424805,4277.571289,4460.390625,4376.137695,...,618.796570,623.717529,832.035965,837.286621,833.581222,835.270798,838.281891,838.850265,1036.590759,837.970154
6276,52236.12891,8721.544922,8302.000977,8860.457031,8695.295898,8413.992188,8811.828125,4392.283691,4407.360352,4402.760254,...,619.826904,625.432739,831.679153,836.998993,836.678360,835.223206,836.229553,837.833313,1037.438171,837.910950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4037,52014.23438,8664.579102,8248.761719,8883.065430,8651.513672,8428.266602,8912.579102,4269.951172,4464.497559,4394.032715,...,621.362122,624.697266,831.648880,836.193603,836.181824,837.989838,837.908020,837.515579,1035.859192,838.213989
4068,52146.47266,8735.132813,8290.149414,8849.363281,8579.207031,8412.826172,8885.934570,4267.597656,4466.091309,4332.597656,...,619.380920,623.018433,832.671402,837.771728,836.042419,836.434891,837.183701,837.537720,1034.487366,837.975586
1570,52102.35547,8792.959961,8265.441406,8828.396484,8606.086914,8478.452148,8863.905273,4290.414551,4440.374512,4364.575195,...,614.036804,618.634582,831.449036,836.301376,837.730957,836.726044,837.694641,837.110382,1019.283203,838.286316
2062,52134.34375,8771.809570,8349.643555,8818.755859,8541.891602,8380.604492,8922.326172,4312.419434,4451.227051,4362.869629,...,613.681213,618.012573,833.040756,837.591705,833.833176,834.867889,837.279953,838.836548,1021.320709,837.952759
5272,52195.58203,8813.144531,8261.952148,8791.002930,8561.758789,8474.772461,8871.682617,4290.803223,4469.081055,4339.306641,...,618.597961,624.693420,832.129700,837.677978,833.018936,836.567001,838.603836,838.318832,1035.990540,838.014832

In [56]:
df_scaled = scaler.transform(x_train2)

In [57]:
df_scaled

array([[ 0.26313246,  0.70895728,  0.15895497, ..., -0.96801679,
        -1.13721319, -0.26424849],
       [ 0.62704343,  0.86527171,  0.36231776, ..., -0.94834012,
         0.81691125,  0.30904951],
       [-0.16450547, -0.44734897,  0.24261255, ...,  1.09257932,
        -0.76786007, -0.06933333],
       ...,
       [ 0.03309239,  0.66269371, -0.18017818, ..., -0.33320546,
        -0.82778809,  0.2819877 ],
       [ 0.10278525,  0.48755362,  0.53090295, ...,  0.41576638,
        -0.62382743,  0.04229116],
       [ 0.23620508,  0.82983612, -0.20964471, ...,  0.19113307,
         0.84466814,  0.08689705]])

In [ ]:
def log_transform(x):
    return np.log(x+1)

df_log = log_transform(df_scaled)

/var/folders/km/r41513gd0glcqg29cdttf5mm0000gn/T/ipykernel_5978/2685063011.py:2: RuntimeWarning: invalid value encountered in log
  return np.log(x+1)

In [61]:
df_log

array([[ 0.23359472,  0.53588341,  0.14751871, ..., -3.44254429,
                nan, -0.30686284],
       [ 0.48676452,  0.62340673,  0.30918749, ..., -2.96307382,
         0.59713795,  0.26930131],
       [-0.17973148, -0.59302852,  0.21721606, ...,  0.73839743,
        -1.46041495, -0.0718541 ],
       ...,
       [ 0.03255662,  0.508439  , -0.19866825, ..., -0.40527332,
        -1.75902955,  0.24841176],
       [ 0.09783902,  0.39713291,  0.42585772, ...,  0.34767099,
        -0.97770727,  0.04142133],
       [ 0.21204627,  0.60422641, -0.2352727 , ...,  0.17490502,
         0.61229939,  0.0833269 ]])