In [113]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

In [114]:
df = pd.read_csv("/Users/miaalfonso/Desktop/HW/Assignment2/Data_Plant.csv")
#/Data_Plant.csv Assignment2/Data_Plant.csv

In [ ]:
#Problem 1
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7199 entries, 0 to 7198
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   39527.25     7199 non-null   float64
 1   27.46636009  7198 non-null   float64
 2   27.62891006  7198 non-null   float64
 3   8.822265625  7199 non-null   float64
 4   5.396483898  7199 non-null   float64
 5   1691.651001  7199 non-null   float64
 6   7.366691113  7199 non-null   float64
 7   78.55264282  7199 non-null   float64
 8   13.51465034  7199 non-null   float64
 9   36.84375     7199 non-null   float64
 10  49.53516006  7198 non-null   float64
 11  89.08007813  7199 non-null   float64
 12  92.59375     7199 non-null   float64
 13  99.771492    7198 non-null   float64
 14  8588.513672  7198 non-null   float64
 15  60.45621872  7199 non-null   float64
 16  45.68021011  7198 non-null   float64
 17  3.066406012  7199 non-null   float64
 18  55.95146179  7198 non-null   float64
 19  71.27528381  7199 non-null   float64
 20  30.65937042  7199 non-null   float64
 21  30.5925808   7198 non-null   float64
 22  375845.3125  7199 non-null   float64
 23  45.99155045  7199 non-null   float64
 24  3.265625     7199 non-null   float64
 25  2.267400026  7198 non-null   float64
 26  1.721600056  7197 non-null   float64
dtypes: float64(27)
memory usage: 1.5 MB
None

In [116]:
df.head(10)

,39527.25,27.46636009,27.62891006,8.822265625,5.396483898,1691.651001,7.366691113,78.55264282,13.51465034,36.84375,...,3.066406012,55.95146179,71.27528381,30.65937042,30.5925808,375845.3125,45.99155045,3.265625,2.267400026,1.721600056
0,39527.25208,27.471821,27.566410,8.869142,5.396484,1698.780029,7.370453,78.717918,13.69824,36.843750,...,3.037109,55.956829,71.275284,30.619141,30.603519,380038.1875,45.984451,3.265625,2.267195,1.720545
1,39527.25417,27.477289,27.539061,8.734374,5.404296,1703.457031,7.374215,78.399452,13.74219,36.843750,...,3.066406,55.962200,71.275284,30.607910,30.572269,389348.0000,45.977341,3.243652,NaN,1.700500
2,39527.25625,27.482759,NaN,8.734374,5.427734,1699.296997,7.377976,78.485107,13.86719,36.843750,...,3.059082,55.967579,71.275284,30.592581,30.598829,385134.5938,45.970242,3.265625,2.263300,1.700500
3,39527.25833,27.488220,27.476561,8.756347,5.427734,1686.083984,7.381738,78.517532,13.74219,36.843750,...,3.037109,55.972950,71.275284,30.648439,30.616800,359803.0000,45.963131,3.265625,2.263300,1.700500
4,39527.26042,27.493690,27.468750,8.756347,5.427734,1691.494019,7.385500,78.575523,13.68359,36.843750,...,3.037109,55.978321,71.275284,30.632811,30.576960,376974.5938,45.956032,3.265625,2.263300,1.700500
5,39527.26250,27.499161,27.737310,8.822266,5.427734,1684.032959,7.389262,78.636162,13.62109,36.843750,...,3.037109,55.983688,71.275284,30.632811,30.572269,373914.4063,45.948929,3.265625,2.263300,1.700500
6,39527.26458,27.503080,28.640631,9.648439,5.488281,1704.883057,7.393024,78.628601,13.57421,36.937500,...,3.128906,55.989059,71.275284,30.690620,30.648439,397545.1875,45.941818,3.296875,2.263910,1.703245
7,39527.26667,27.496700,28.394529,9.537109,5.457031,1686.991943,7.396786,78.825798,14.23437,37.119141,...,3.059082,55.994431,71.275284,30.664061,30.616800,384739.3125,45.934719,3.320313,2.275500,1.755400
8,39527.26875,27.490320,28.534180,9.191404,5.548828,1692.764038,7.400548,78.663643,14.66406,37.212891,...,3.158203,55.999802,71.275284,30.619141,30.592581,377052.1875,46.068630,3.289063,2.275500,1.755400
9,39527.27083,27.483950,28.394529,9.466796,5.526855,1692.772949,7.404310,78.446083,14.84766,37.306641,...,3.150879,56.005169,71.275284,30.603519,30.590231,390613.3125,46.229080,3.328125,2.275500,1.755400

In [117]:
df.describe()

,39527.25,27.46636009,27.62891006,8.822265625,5.396483898,1691.651001,7.366691113,78.55264282,13.51465034,36.84375,...,3.066406012,55.95146179,71.27528381,30.65937042,30.5925808,375845.3125,45.99155045,3.265625,2.267400026,1.721600056
count,7199.000000,7198.000000,7198.000000,7199.000000,7199.000000,7199.000000,7199.000000,7199.000000,7199.000000,7199.000000,...,7199.000000,7198.000000,7199.000000,7199.000000,7198.000000,7199.000000,7199.000000,7199.000000,7198.000000,7197.000000
mean,39534.750000,27.127295,27.953209,9.593198,6.395699,1701.915367,11.555007,76.332696,18.356032,37.815861,...,3.620778,52.985809,70.771369,30.648593,30.609367,386035.274340,45.167884,3.841032,2.114043,0.692348
std,4.329826,0.674680,0.698533,0.630545,0.952640,99.738546,2.901431,3.595688,3.648891,1.768092,...,0.623456,1.915064,1.725054,0.192165,0.194832,18811.255389,14.682053,0.619553,0.637675,17.474702
min,39527.252080,24.231501,24.593750,7.673828,4.951172,687.060486,6.780738,18.643391,8.441406,35.882809,...,2.455078,47.744381,0.000000,29.974609,30.035160,236985.406300,12.223560,0.000000,-8.956800,-320.799988
25%,39531.001040,26.652867,27.507811,9.191404,5.640625,1659.447998,9.108021,74.057091,15.921870,37.166019,...,3.158203,51.530783,71.275284,30.534136,30.497549,375581.046900,38.216480,3.388672,1.930599,1.390500
50%,39534.750000,27.109890,27.906250,9.570802,6.177734,1697.920044,11.137910,76.542381,19.292971,37.535160,...,3.511719,53.136414,71.275284,30.603519,30.573830,386836.500000,47.806690,3.737500,2.160500,1.642300
75%,39538.498960,27.518567,28.394529,9.923826,6.958984,1751.557495,13.789635,78.800842,21.316410,37.904301,...,4.030078,54.495871,71.275284,30.724609,30.679689,397080.296900,55.019815,4.246094,2.328500,1.789600
max,39542.247920,47.017712,42.443359,17.277340,19.515141,2235.039063,26.766680,84.796471,29.253910,64.715332,...,15.594240,57.336620,71.275284,31.686710,31.644920,643457.375000,90.493187,14.015130,4.172300,135.899994

In [118]:
df.shape

(7199, 27)

In [119]:
df.columns = df.columns.str.upper()

In [ ]:
#Problem 2
df.isnull().sum().sum()

11

In [121]:
df_mean = df.fillna(df.mean())

In [122]:
df_drop_dup = df.drop_duplicates()

In [ ]:
#Problem 3
x_train, x_temp = train_test_split(df, test_size = 0.3, random_state=42)
#
x_val, x_test = train_test_split(x_temp, test_size=0.5, random_state=42)

In [124]:
print(len(x_train))
print(len(x_test))
print(len(x_val))

5039
1080
1080

In [125]:
x_train.head()

,39527.25,27.46636009,27.62891006,8.822265625,5.396483898,1691.651001,7.366691113,78.55264282,13.51465034,36.84375,...,3.066406012,55.95146179,71.27528381,30.65937042,30.5925808,375845.3125,45.99155045,3.265625,2.267400026,1.721600056
1224,39529.80208,26.964970,28.027340,10.433590,7.169141,1716.454956,14.712780,73.926971,21.898439,37.857422,...,3.955078,51.273380,70.198029,30.603519,30.519039,378222.1875,15.093710,4.216797,1.7952,1.59850
142,39527.54792,27.113880,28.703131,9.994142,7.411621,1755.282959,16.069889,70.363358,22.386721,37.904301,...,4.224121,55.700008,65.384720,30.556641,30.541019,375588.5000,14.473050,4.384766,2.6402,2.55110
1490,39530.35625,26.465530,27.382811,9.050780,5.365234,1698.114990,7.595062,79.663452,12.304690,36.802731,...,2.953125,55.273960,71.275284,30.629391,30.587891,374298.6875,53.150581,3.158203,2.2188,1.73510
7179,39542.20833,26.863079,27.906250,9.560548,5.616015,1583.935059,8.373703,78.741470,11.320310,37.031250,...,3.281250,51.126560,71.275284,30.818359,30.818359,361322.4063,52.393059,3.527344,2.3296,0.98976
2663,39532.80000,27.377840,28.304689,10.111330,6.054688,1721.592041,10.786220,74.878487,18.582821,38.081249,...,3.464844,54.765240,71.275284,30.802740,30.710939,367724.4063,42.646030,3.757813,2.1671,1.67250

In [126]:
x_val.head()

,39527.25,27.46636009,27.62891006,8.822265625,5.396483898,1691.651001,7.366691113,78.55264282,13.51465034,36.84375,...,3.066406012,55.95146179,71.27528381,30.65937042,30.5925808,375845.3125,45.99155045,3.265625,2.267400026,1.721600056
6037,39539.82917,26.152800,26.984381,8.734374,6.316406,1564.453003,11.74887,75.086166,19.848440,36.843750,...,3.469532,54.354671,71.275284,30.587891,30.587891,386007.4063,33.343941,3.757813,3.4261,3.67770
167,39527.60000,27.603710,28.335939,10.134760,6.261718,1736.826050,12.48243,71.556641,20.703131,38.179691,...,3.451172,55.501080,65.729187,30.623541,30.576960,360985.0000,12.996090,3.664063,2.2545,0.73368
4761,39537.17083,26.595160,26.874220,8.318358,5.718750,1642.237061,10.89223,76.098084,18.564060,36.890629,...,2.994921,50.524540,71.275284,30.511721,30.464840,396743.0938,16.170971,3.220703,2.2836,1.10230
5477,39538.66250,27.269621,28.394529,10.246090,6.632325,1725.635010,12.97583,76.921127,21.222660,37.722660,...,3.726563,54.985950,71.275284,30.556641,30.511721,404324.5000,53.745789,3.849609,2.5745,1.74100
1744,39530.88542,27.041849,28.643749,10.111330,6.835938,1654.208984,13.61673,75.956062,21.222660,37.857422,...,3.986328,55.347610,69.921387,30.629391,30.603519,382729.0938,15.385480,4.201172,2.3170,1.52950

In [ ]:
#Problem 4
scaler = StandardScaler().fit(x_train)

In [128]:
x_train

,39527.25,27.46636009,27.62891006,8.822265625,5.396483898,1691.651001,7.366691113,78.55264282,13.51465034,36.84375,...,3.066406012,55.95146179,71.27528381,30.65937042,30.5925808,375845.3125,45.99155045,3.265625,2.267400026,1.721600056
1224,39529.80208,26.964970,28.027340,10.433590,7.169141,1716.454956,14.712780,73.926971,21.898439,37.857422,...,3.955078,51.273380,70.198029,30.603519,30.519039,378222.1875,15.093710,4.216797,1.7952,1.59850
142,39527.54792,27.113880,28.703131,9.994142,7.411621,1755.282959,16.069889,70.363358,22.386721,37.904301,...,4.224121,55.700008,65.384720,30.556641,30.541019,375588.5000,14.473050,4.384766,2.6402,2.55110
1490,39530.35625,26.465530,27.382811,9.050780,5.365234,1698.114990,7.595062,79.663452,12.304690,36.802731,...,2.953125,55.273960,71.275284,30.629391,30.587891,374298.6875,53.150581,3.158203,2.2188,1.73510
7179,39542.20833,26.863079,27.906250,9.560548,5.616015,1583.935059,8.373703,78.741470,11.320310,37.031250,...,3.281250,51.126560,71.275284,30.818359,30.818359,361322.4063,52.393059,3.527344,2.3296,0.98976
2663,39532.80000,27.377840,28.304689,10.111330,6.054688,1721.592041,10.786220,74.878487,18.582821,38.081249,...,3.464844,54.765240,71.275284,30.802740,30.710939,367724.4063,42.646030,3.757813,2.1671,1.67250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,39535.11042,27.079130,28.121090,9.648439,6.031739,1654.951050,11.064820,76.174744,19.078131,37.212891,...,3.373047,51.892262,71.275284,30.507030,30.525391,376025.9063,62.427132,3.650391,2.0361,1.87020
5191,39538.06667,27.545870,28.488279,10.464350,7.158204,1722.608032,13.388790,72.282600,21.621090,39.925781,...,4.109375,48.992809,69.390831,30.724609,30.687500,378881.3125,40.906158,4.369141,2.1605,1.02840
5226,39538.13958,27.823280,28.855471,10.890620,5.826172,1829.344971,7.777565,80.074387,11.597660,46.177731,...,3.451172,48.757259,71.275284,30.840340,30.810551,355841.0000,45.087872,3.679688,1.1693,1.07890
5390,39538.48125,27.786190,28.886721,9.009765,6.867188,1634.911987,9.796403,81.324318,16.911131,38.361328,...,4.339844,55.124779,71.275284,31.615231,31.583990,358808.4063,56.763062,4.583984,3.3035,1.53030
860,39529.04375,27.736481,28.703131,9.789063,5.947266,1706.933960,8.378467,80.219254,16.808590,37.488281,...,3.511719,52.504791,71.275284,30.740231,30.681250,399967.5938,56.215618,3.710938,2.2046,1.63180

In [ ]:
df_scaled = scaler.transform(x_train)

In [130]:
df_scaled

array([[-1.15442835, -0.25071415,  0.12133967, ...,  0.57697576,
        -0.49476244,  0.04567541],
       [-1.67797257, -0.01209719,  1.12684229, ...,  0.84145414,
         0.82185437,  0.10665686],
       [-1.02571854, -1.0510248 , -0.83764937, ..., -1.08984874,
         0.1652601 ,  0.05441997],
       ...,
       [ 0.78201358,  1.12465872,  1.35350743, ..., -0.26873684,
        -1.4699939 ,  0.01241281],
       [ 0.86136879,  1.06522454,  1.400004  , ...,  1.15513541,
         1.85535978,  0.04130954],
       [-1.33055572,  0.98556941,  1.12684229, ..., -0.2195317 ,
         0.14313475,  0.04780714]])

In [131]:
def log_transform(x):
    return np.log(x+1)

df_log = log_transform(df_scaled)

/var/folders/km/r41513gd0glcqg29cdttf5mm0000gn/T/ipykernel_6700/2685063011.py:2: RuntimeWarning: invalid value encountered in log
  return np.log(x+1)

In [132]:
df_log

array([[        nan, -0.28863473,  0.1145241 , ...,  0.45550894,
        -0.68272654,  0.04466301],
       [        nan, -0.01217096,  0.75463839, ...,  0.61055555,
         0.59985487,  0.10134363],
       [        nan,         nan, -1.8179969 , ...,         nan,
         0.15294432,  0.05299083],
       ...,
       [ 0.57774395,  0.75361119,  0.85590674, ..., -0.31298188,
                nan,  0.0123364 ],
       [ 0.62131213,  0.72523896,  0.8754704 , ...,  0.76785356,
         1.04919785,  0.04047909],
       [        nan,  0.68590573,  0.75463839, ..., -0.24786115,
         0.13377427,  0.04669955]])